### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by Gbaja** [BridgeMap/coming-soon-page#6]
At the moment, the email "hello@bridgemap.org" that came with the purchase of domain only has 2GB.

We either want to see if we can set up a redirect to a standard gmail account or whether we should set up a g suite account for 1 user to start with.

**Comment by sophielevens** [comment]
A Gmail account has been created, but our emails are still getting saved in the IONOS mail storage folder. We can use the Gmail account to sign up for accounts online but we will need to review this if we end up using all the storage space in IONOS.
